name: Lint Python

on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: Linting & Formatting with autopep8, pyupgrade, black, isort, and flynt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "**.py"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install autopep8 pyupgrade black isort flynt

      # Step 1: Run autopep8 for formatting
      - name: Run autopep8 on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          autopep8 --in-place --aggressive "${changed_files[@]}"

      # Step 2: Run pyupgrade to ensure Python 3.6+ compatibility
      - name: Run pyupgrade on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          for file in "${changed_files[@]}"; do
            pyupgrade --py36-plus "$file"
          done

      # Step 3: Run black for consistent formatting
      - name: Run black on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          black "${changed_files[@]}"

      # Step 4: Run isort to sort imports
      - name: Run isort on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          isort "${changed_files[@]}"

      # Step 5: Run flynt to convert string formatting to f-strings
      - name: Run flynt on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          flynt "${changed_files[@]}"
